/*========================================================================
        TradeXpress        

        File:		tr_rte_globals.c
        Author:		Jean-François CLAVIER (JFC)
        Date:		Fri Sept 09 2011

	This file declares all RTE globals except those generated by the rte compiler.
        
	Created for BugZ_9980_OPEN_DB.

        Copyright (c) 2010 GenerixGroup
==========================================================================
        Record all changes here and update the above string accordingly.
        09.09.2011/JFC    Created.
==========================================================================*/
#include "conf/local_config.h"
#include "tr_logsystem.h"

#define MAX_CHAR_DIRS 16
char *        tr_matchBuf;        /* Used for line matching */
char *        tr_returnBuffer;    /* Contains possible "unread" */
int	          tr_winSize;         /* Window max size, 0 if not used */
int	          tr_curHighLine;     /* Highest line in current window */
char          tr_optArray[26];    /* Command line options A-Z */
int	          tr_lastCall;        /* Used in MOTIF-debugger */
char *        tr_programName;     /**/
char *        tr_ADS;             /* Decimal separator used in application file */
char *        tr_MDS;             /* Primary Decimal separator used in EDI-msg */
char *        tr_MDS_IN = NULL;   /* Primary Decimal separator used in received EDI-msg */
char *        tr_progName;        /* Name of the running program.  */
extern int    tr_sourceLine;      /* Current source code line */
double        tr_errorLevel;      /* To print or not, to exit or not */
double        tr_ARGC;            /* Number of arguments (in addition to options and parameters) */
char *        tr_parameterFile;   /* Filename for command line parameters */
int           tr_updateParams;    /* Flag telling whether parameter file is updated */
int           tr_unBufferedOutput;/* Flag telling whether the output is buffered or not */
extern int    tr_processErroneous;/* A user modifiable variable to indicate where */
				                  /* erroneous messages are directed */
extern int    tr_writeSegStatus;  /* The status from the last tr_writesegment() */
extern char * tr_lastSegment;     /* The segment data in string format for last read */
char *        tr_charSet;         /* Filename for the compiled character set */
/* Syntax to syntax needs */
char*         tr_Incoming_CharSet;
char*         tr_Incoming_CharSetDirs[MAX_CHAR_DIRS+2];
char*         tr_Outgoing_CharSet;
char*         tr_Outgoing_CharSetDirs[MAX_CHAR_DIRS+2];

/* RTE will set Syntax to 1 on receiving and building messages */
short int tr_in_EDISyntax = 0;
short int tr_out_EDISyntax = 0;
short int tr_in_XMLSyntax = 0;
short int tr_out_XMLSyntax = 0;
int	tr_In = 0;                    /* Set to 1 when processing received message, 0 for building message. */

LogSysHandle  paramArrayLog;

/* from tr_edifact.h */
double tr_syntax = 0;             /* Current EDI syntax and version 4.00/JH	*/
double tr_arrComponents = 100.0;  /* ARR segment component maxcount 4.00/JH	*/
double tr_arrComposites = 100.0;  /* ARR segment composite maxcount 4.00/JH	*/

